//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 01:24:11 PM CEST 
//


package urouen.STB.model;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClientType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClientType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://univ.fr/stb}Entite"/>
 *         &lt;element ref="{http://univ.fr/stb}Contact"/>
 *         &lt;element ref="{http://univ.fr/stb}CodePostal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientType", propOrder = {
    "entite",
    "contact",
    "codePostal"
})
@Entity
@Table(name="ClientType")
public class ClientType {

	@XmlTransient
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
    @XmlElement(name = "Entite", required = true)
    @Column(name = "Entite")
    protected String entite;
    @XmlElement(name = "Contact", required = true)
    @OneToOne(cascade = { CascadeType.PERSIST, CascadeType.REMOVE })
    protected ContactType contact;
    @XmlElement(name = "CodePostal")
    @Column(name = "CodePostal")
    protected int codePostal;
    
    
    public ClientType() {
		super();
	}

	public ClientType(String entite, ContactType contact, int codePostal) {
		super();
		this.entite = entite;
		this.contact = contact;
		this.codePostal = codePostal;
	}

	/**
     * Gets the value of the entite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntite() {
        return entite;
    }

    /**
     * Sets the value of the entite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntite(String value) {
        this.entite = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactType }
     *     
     */
    public ContactType getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactType }
     *     
     */
    public void setContact(ContactType value) {
        this.contact = value;
    }

    /**
     * Gets the value of the codePostal property.
     * 
     */
    public int getCodePostal() {
        return codePostal;
    }

    /**
     * Sets the value of the codePostal property.
     * 
     */
    public void setCodePostal(int value) {
        this.codePostal = value;
    }

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
    

}
