//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 01:24:11 PM CEST 
//

package urouen.STB.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ExigenceFonctionnelleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ExigenceFonctionnelleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://univ.fr/stb}Identifiant"/>
 *         &lt;element ref="{http://univ.fr/stb}Description"/>
 *         &lt;element ref="{http://univ.fr/stb}Priorite"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExigenceFonctionnelleType", propOrder = { "identifiant", "description", "priorite" })
@Entity
@Table(name = "ExigenceFonctionnelleType")
public class ExigenceFonctionnelleType {

	@XmlElement(name = "Identifiant", required = true)
	@Id
	@Column(name = "Identifiant")
	protected String identifiant;
	@XmlElement(name = "Description", required = true)
	@Column(name = "Description")
	protected String description;
	@XmlElement(name = "Priorite")
	@Column(name = "Priorite")
	protected int priorite;

	public ExigenceFonctionnelleType() {
		super();
	}

	public ExigenceFonctionnelleType(String identifiant, String description, int priorite) {
		super();
		this.identifiant = identifiant;
		this.description = description;
		this.priorite = priorite;
	}

	/**
	 * Gets the value of the identifiant property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdentifiant() {
		return identifiant;
	}

	/**
	 * Sets the value of the identifiant property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdentifiant(String value) {
		this.identifiant = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the priorite property.
	 * 
	 */
	public int getPriorite() {
		return priorite;
	}

	/**
	 * Sets the value of the priorite property.
	 * 
	 */
	public void setPriorite(int value) {
		this.priorite = value;
	}

}
