//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 01:24:11 PM CEST 
//

package urouen.STB.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for FonctionaliteType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="FonctionaliteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://univ.fr/stb}Description"/>
 *         &lt;element ref="{http://univ.fr/stb}ExigenceFonctionnelle" maxOccurs="unbounded" minOccurs="2"/>
 *       &lt;/sequence>
 *       &lt;attribute name="priorite" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FonctionaliteType", propOrder = { "description", "exigenceFonctionnelle" })
@Entity
@Table(name = "FonctionaliteType")
public class FonctionaliteType {

	@XmlTransient
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	@XmlElement(name = "Description", required = true)
	@Column(name = "Description")
	protected String description;
	@XmlElement(name = "ExigenceFonctionnelle", required = true)

	@OneToMany(cascade = { CascadeType.PERSIST, CascadeType.REMOVE })
	protected List<ExigenceFonctionnelleType> exigenceFonctionnelle;
	@XmlAttribute
	protected Integer priorite;

	public FonctionaliteType() {
		super();
	}

	public FonctionaliteType(String description, List<ExigenceFonctionnelleType> exigenceFonctionnelle,
			Integer priorite) {
		super();
		this.description = description;
		this.exigenceFonctionnelle = exigenceFonctionnelle;
		this.priorite = priorite;
	}
	
	
	

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setExigenceFonctionnelle(List<ExigenceFonctionnelleType> exigenceFonctionnelle) {
		this.exigenceFonctionnelle = exigenceFonctionnelle;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the exigenceFonctionnelle property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the exigenceFonctionnelle property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getExigenceFonctionnelle().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ExigenceFonctionnelleType }
	 * 
	 * 
	 */
	public List<ExigenceFonctionnelleType> getExigenceFonctionnelle() {
		if (exigenceFonctionnelle == null) {
			exigenceFonctionnelle = new ArrayList<ExigenceFonctionnelleType>();
		}
		return this.exigenceFonctionnelle;
	}

	/**
	 * Gets the value of the priorite property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getPriorite() {
		return priorite;
	}

	/**
	 * Sets the value of the priorite property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setPriorite(Integer value) {
		this.priorite = value;
	}

}
