//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 01:24:11 PM CEST 
//


package urouen.STB.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the urouen.STB.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Entite_QNAME = new QName("http://univ.fr/stb", "Entite");
    private final static QName _Contact_QNAME = new QName("http://univ.fr/stb", "Contact");
    private final static QName _Date_QNAME = new QName("http://univ.fr/stb", "Date");
    private final static QName _Commmentaire_QNAME = new QName("http://univ.fr/stb", "Commmentaire");
    private final static QName _Gender_QNAME = new QName("http://univ.fr/stb", "gender");
    private final static QName _ExigenceFonctionnelle_QNAME = new QName("http://univ.fr/stb", "ExigenceFonctionnelle");
    private final static QName _Stb_QNAME = new QName("http://univ.fr/stb", "stb");
    private final static QName _Titre_QNAME = new QName("http://univ.fr/stb", "Titre");
    private final static QName _Description_QNAME = new QName("http://univ.fr/stb", "Description");
    private final static QName _CodePostal_QNAME = new QName("http://univ.fr/stb", "CodePostal");
    private final static QName _Identifiant_QNAME = new QName("http://univ.fr/stb", "Identifiant");
    private final static QName _Client_QNAME = new QName("http://univ.fr/stb", "Client");
    private final static QName _Equipe_QNAME = new QName("http://univ.fr/stb", "Equipe");
    private final static QName _Version_QNAME = new QName("http://univ.fr/stb", "Version");
    private final static QName _Fonctionnalite_QNAME = new QName("http://univ.fr/stb", "Fonctionnalite");
    private final static QName _Priorite_QNAME = new QName("http://univ.fr/stb", "Priorite");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: urouen.STB.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FonctionaliteType }
     * 
     */
    public FonctionaliteType createFonctionaliteType() {
        return new FonctionaliteType();
    }

    /**
     * Create an instance of {@link StbType }
     * 
     */
    public StbType createStbType() {
        return new StbType();
    }

    /**
     * Create an instance of {@link ExigenceFonctionnelleType }
     * 
     */
    public ExigenceFonctionnelleType createExigenceFonctionnelleType() {
        return new ExigenceFonctionnelleType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link ClientType }
     * 
     */
    public ClientType createClientType() {
        return new ClientType();
    }

    /**
     * Create an instance of {@link EquipeType }
     * 
     */
    public EquipeType createEquipeType() {
        return new EquipeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Entite")
    public JAXBElement<String> createEntite(String value) {
        return new JAXBElement<String>(_Entite_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Contact")
    public JAXBElement<ContactType> createContact(ContactType value) {
        return new JAXBElement<ContactType>(_Contact_QNAME, ContactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Date")
    public JAXBElement<XMLGregorianCalendar> createDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Date_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Commmentaire")
    public JAXBElement<String> createCommmentaire(String value) {
        return new JAXBElement<String>(_Commmentaire_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "gender")
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExigenceFonctionnelleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "ExigenceFonctionnelle")
    public JAXBElement<ExigenceFonctionnelleType> createExigenceFonctionnelle(ExigenceFonctionnelleType value) {
        return new JAXBElement<ExigenceFonctionnelleType>(_ExigenceFonctionnelle_QNAME, ExigenceFonctionnelleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StbType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "stb")
    public JAXBElement<StbType> createStb(StbType value) {
        return new JAXBElement<StbType>(_Stb_QNAME, StbType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Titre")
    public JAXBElement<String> createTitre(String value) {
        return new JAXBElement<String>(_Titre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "CodePostal")
    public JAXBElement<Integer> createCodePostal(Integer value) {
        return new JAXBElement<Integer>(_CodePostal_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Identifiant")
    public JAXBElement<String> createIdentifiant(String value) {
        return new JAXBElement<String>(_Identifiant_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Client")
    public JAXBElement<ClientType> createClient(ClientType value) {
        return new JAXBElement<ClientType>(_Client_QNAME, ClientType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquipeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Equipe")
    public JAXBElement<EquipeType> createEquipe(EquipeType value) {
        return new JAXBElement<EquipeType>(_Equipe_QNAME, EquipeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FonctionaliteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Fonctionnalite")
    public JAXBElement<FonctionaliteType> createFonctionnalite(FonctionaliteType value) {
        return new JAXBElement<FonctionaliteType>(_Fonctionnalite_QNAME, FonctionaliteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://univ.fr/stb", name = "Priorite")
    public JAXBElement<Integer> createPriorite(Integer value) {
        return new JAXBElement<Integer>(_Priorite_QNAME, Integer.class, null, value);
    }

}
